import pandas as pd
import numpy as np
import ta
import yaml
import os

def load_config(config_path="nifty_rl_trader/config/settings.yaml"):
    with open(config_path, "r") as f:
        return yaml.safe_load(f)

def load_and_clean_data(file_path):
    """
    Loads raw 1-minute Nifty Spot OHLCV, parses dates, and filters non-market minutes.
    """
    df = pd.read_csv(file_path)

    # Standardize column names
    df.columns = df.columns.str.lower()

    # Parse dates (assuming 'date' column format: DD-MM-YYYY HH:MM)
    df['date'] = pd.to_datetime(df['date'], format='%d-%m-%Y %H:%M')
    df = df.sort_values('date').reset_index(drop=True)

    # Ensure timezone awareness (Asia/Kolkata)
    if df['date'].dt.tz is None:
        df['date'] = df['date'].dt.tz_localize('Asia/Kolkata')

    # Extract time components
    df['time'] = df['date'].dt.time

    # Filter market hours (09:15 to 15:30 IST)
    market_open = pd.to_datetime('09:15').time()
    market_close = pd.to_datetime('15:30').time()
    df = df[(df['time'] >= market_open) & (df['time'] <= market_close)].copy()

    # Drop rows with NaN in critical columns
    df = df.dropna(subset=['open', 'high', 'low', 'close']).copy()

    return df

def add_technical_features(df):
    """
    Adds technical indicators and temporal encodings to the dataframe.
    """
    df = df.copy()

    # Log returns
    for window in [1, 5, 15, 60]:
        df[f'log_return_{window}m'] = np.log(df['close'] / df['close'].shift(window))

    # Volatility & Trend
    df['atr_14'] = ta.volatility.AverageTrueRange(
        high=df['high'], low=df['low'], close=df['close'], window=14
    ).average_true_range() / df['close'] # Normalized by close

    df['rsi_14'] = ta.momentum.RSIIndicator(close=df['close'], window=14).rsi() / 100.0 # Normalized to [0,1]

    macd = ta.trend.MACD(close=df['close'])
    df['macd_hist'] = macd.macd_diff() / df['close'] # Normalized

    bollinger = ta.volatility.BollingerBands(close=df['close'])
    df['bb_width'] = (bollinger.bollinger_hband() - bollinger.bollinger_lband()) / df['close']

    # VWAP Divergence
    # Approximating VWAP for daily session
    df['date_only'] = df['date'].dt.date
    df['typical_price'] = (df['high'] + df['low'] + df['close']) / 3
    # If volume is 0 in spot, fallback to uniform weighting
    if df['volume'].sum() == 0:
        df['cum_pv'] = df.groupby('date_only')['typical_price'].cumsum()
        df['cum_vol'] = df.groupby('date_only').cumcount() + 1
    else:
        df['cum_pv'] = df.groupby('date_only').apply(lambda x: (x['typical_price'] * x['volume']).cumsum()).reset_index(level=0, drop=True)
        df['cum_vol'] = df.groupby('date_only')['volume'].cumsum()

    df['vwap'] = df['cum_pv'] / df['cum_vol']
    df['vwap_div'] = (df['close'] - df['vwap']) / df['vwap']

    # Temporal Encoding
    minutes_from_open = (pd.to_timedelta(df['date'].dt.strftime('%H:%M:%S')) - pd.to_timedelta('09:15:00')).dt.total_seconds() / 60.0
    total_market_minutes = 375 # 09:15 to 15:30 is 6.25 hours = 375 minutes

    df['time_sin'] = np.sin(2 * np.pi * minutes_from_open / total_market_minutes)
    df['time_cos'] = np.cos(2 * np.pi * minutes_from_open / total_market_minutes)

    # Clean up temp columns
    df.drop(columns=['date_only', 'typical_price', 'cum_pv', 'cum_vol', 'vwap'], inplace=True, errors='ignore')

    # Drop NaNs generated by rolling windows
    df = df.dropna().reset_index(drop=True)
    return df

def split_and_save_data(df, config):
    """
    Splits the data sequentially and saves to parquet files.
    Train (2015-2023), Validation (2024-2025), Test (2026+)
    """
    out_dir = config['settings']['data_paths']['processed_data']
    os.makedirs(out_dir, exist_ok=True)

    years = df['date'].dt.year

    train_df = df[years <= 2023]
    val_df = df[(years >= 2024) & (years <= 2025)]
    test_df = df[years >= 2026]

    # If there is no data for 2026+, we'll create a generic test split
    if test_df.empty:
        # Check if we have 2024, maybe data only goes up to 2024?
        if val_df.empty:
             # Data is very old, split by ratio 70/15/15
             total = len(df)
             train_idx = int(total * 0.7)
             val_idx = int(total * 0.85)
             train_df = df.iloc[:train_idx]
             val_df = df.iloc[train_idx:val_idx]
             test_df = df.iloc[val_idx:]
        else:
             # Just use 2025 for test if available, else standard ratio for the rest
             pass

    train_df.to_parquet(os.path.join(out_dir, "train.parquet"))
    val_df.to_parquet(os.path.join(out_dir, "val.parquet"))
    test_df.to_parquet(os.path.join(out_dir, "test.parquet"))

    print(f"Data saved. Train: {len(train_df)}, Val: {len(val_df)}, Test: {len(test_df)}")

if __name__ == "__main__":
    config = load_config()
    raw_path = config['settings']['data_paths']['raw_data']
    print(f"Loading data from {raw_path}...")
    df = load_and_clean_data(raw_path)
    print("Adding technical features...")
    df = add_technical_features(df)
    print("Splitting and saving data...")
    split_and_save_data(df, config)
